api/php/README.md
api/php/app.php

Fix php example

---

api/node/README.md
api/node/package.json

@bhelx I went with the repo here: https://github.com/cgerrior/node-recurly (fork of https://github.com/breadbaker/node-recurly) as there are confirmed reports of it working. I also added a User-Agent string in "my" node-recurly.

changes node-recurly module

---

public/advanced-bank-account/index.html
public/index.html

Basic form showing use of new bank account token methods.
approvers: @chrissrogers

setting up basic bank account example form

---

public/advanced-pricing/index.html
public/advanced-tax/index.html
public/minimal/index.html
public/minimal/style.css

Updates HTML and CSS to reflect recurly.js v4

Updates HTML and CSS to reflect recurly.js v4

---

public/advanced-pricing/index.html
public/advanced-tax/index.html

**Dependencies:**
Will require a version of RJS with data collector implemented which will be released soon: https://github.com/recurly/recurly-js/pull/254
**Note**
This will only be useful for merchants with fraud checking enabled. If not enabled, it will trigger an error in the background but otherwise not affect anything.
cc: @jfitisoff @adeitrick @karentobo

Add examples of calling data collector

---

Gemfile
Gemfile.lock
Procfile
README.md
api/README.md
api/ruby-heroku/Gemfile
api/ruby-heroku/Gemfile.lock
api/ruby-heroku/Procfile
api/ruby-heroku/README.md
api/ruby-heroku/app.rb
app.json

Signed-off-by: Christopher Rogers <chrissrogers@gmail.com>

Adds Ruby + Heroku example

---

public/adyen/index.html

fix typo in adyen example

---

api/ruby-heroku/Gemfile
api/ruby-heroku/Gemfile.lock
api/ruby/Gemfile
api/ruby/Gemfile.lock

Updating our ruby gems without taking on any breaking changes.

Fix security warnings

---

api/php/app.php
api/python/README.md
api/python/app.py
public/advanced-bank-account/index.html
public/index.html

When I tried to run the examples in languages other than ruby, there were some issues. This fixes those issues. Explanations in the review.

Fix the examples

---

api/ruby-heroku/app.rb
api/ruby/app.rb
public/3d-secure/authenticate.html
public/3d-secure/index.html
public/minimal/index.html
public/minimal/style.css

- Instead of demonstrating a secondary REST API implementation for 3D Secure, this utilizes redirects. The result is an implementation that is more akin to existing examples, and discards ancillary complications.

Updates 3-D Secure example to use simpler redirect flow

---

api/node/app.js
api/node/package-lock.json
api/node/package.json
api/ruby-heroku/app.rb
api/ruby/app.rb
public/3d-secure/authenticate.html
public/3d-secure/index.html
public/minimal/index.html
public/minimal/style.css

Node example: 3-D Secure

---

api/ruby-heroku/app.rb
api/ruby/app.rb
public/3d-secure/index.html

Removes 3DS client-side impl in index.html

---

api/node/app.js
public/3d-secure/authenticate.html

After this gets reviewed/approved, I'll use this as a baseline and do the same for the other languages/examples.

fixes node 3ds example

---

api/ruby-heroku/app.rb
public/advanced-pricing-items/index.html

- `checkoutPricing` selectively enables the plan HTMLSelectElement
- renames some inputs to match array-like FormData assumptions
- adds error handling capability to example
- disables submit button on submit, re-enables it on error

Adds ability to select no subscriptions to the advanced items pricing example

---

api/node/README.md
api/node/app.js
api/node/package-lock.json
api/node/package.json

- Updates Recurly client to v3
- Updates /api/subscription/new to use Purchase create endpoint
- Updates README

Updates node example

---

api/php/README.md
api/php/app.php
api/php/composer.json
api/php/composer.lock

- Updates Recurly client to v3
- Updates Slim from v3 to v4
- Updates /api/subscription/new to use Purchase create endpoint
- Updates README

Updates PHP example

---

README.md
public/README.md

- Adds notes to main README and ./public README
- Links to examples in the `react-recurly` repo

Adds notes on react-recurly examples

---

api/python/README.md
api/python/app.py

- Examples use v3 API
- Replaces subscription create endpoint with purchase create

Update Python example to align with v3 API

---

api/node/Dockerfile
api/node/package.json
api/python/docker-compose.yml
api/ruby/docker-compose.yml

- Adds missing repository spec in node package.json
- Fixes node package installs on final image and CMD run

Establishes public dirs more explicitly for Docker containers

---

Dockerfile
Procfile
README.md
api/ruby/Dockerfile
api/ruby/Procfile
api/ruby/app.rb
app.json
public/paypal/index.html

- Adds Dockerfile for cloud build spec

Adds Google Cloud Run Button

---

public/adyen/index.html

The click event listener wasn't attaching because the script was running before the document rendered.
This also removes jquery in favor of vanilla JS.

Fixes Adyen example

---

public/account-update/done-white-18dp.svg
public/account-update/index.html
public/account-update/style.css
public/index.html

Added frontend example for updating an account

---

public/bank-redirect/index.html
public/index.html

Bank Redirect example

---

public/google-pay/index.html
public/index.html

Add Google Pay payment example

Add google pay example

---

api/ruby/Gemfile.lock
public/auto-tab/index.html
public/index.html

This highlights the ability of the individual card Elements to introduce behavioral patterns not available to the combined card Element. Namely, between-field interactions and fine controls.

Adds a demo for auto-tabbing behavior

---

api/ruby/Dockerfile
api/ruby/Gemfile
api/ruby/Gemfile.lock
api/ruby/app.rb
api/ruby/docker-compose.yml
public/apple-pay/advanced/index.html
public/apple-pay/direct-tax/index.html
public/apple-pay/shipping/index.html
public/google-pay/direct-tax/index.html
public/index.html
public/style.css

- Apple Pay shipping example
- Apple Pay direct tax example
- Apple Pay advanced example
- Google Pay direct tax/shipping example
- update Ruby example to Ruby 3.2

feat: add more examples for 4.23.0 release

---

api/ruby/app.rb
public/alternative-payment-methods/boleto.html
public/alternative-payment-methods/completed.html
public/alternative-payment-methods/ideal.html
public/index.html

Add examples for iDeal and Boletos payment methods
iDeal:
Boleto:

Add examples for iDeal and Boletos payment methods
